name: flask_web
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - babel=2.16.0=py312haa95532_0
  - bidict=0.21.2=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blinker=1.9.0=py312haa95532_0
  - bottleneck=1.4.2=py312h4b0e54e_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - cffi=1.17.1=py312h827c3e9_1
  - click=8.2.1=py312haa95532_0
  - colorama=0.4.6=py312haa95532_0
  - cryptography=45.0.3=py312h51e0144_0
  - expat=2.7.1=h8ddb27b_0
  - flask=3.1.0=py312haa95532_0
  - flask-socketio=5.5.1=py312haa95532_0
  - flask-sqlalchemy=3.1.1=py312haa95532_0
  - greenlet=3.1.1=py312h5da7b33_0
  - h11=0.16.0=py312haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - itsdangerous=2.2.0=py312haa95532_0
  - jinja2=3.1.6=py312haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - markupsafe=3.0.2=py312h827c3e9_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py312h827c3e9_2
  - mkl_fft=1.3.11=py312h827c3e9_0
  - mkl_random=1.2.8=py312h0158946_0
  - numexpr=2.10.1=py312h4cd664f_0
  - numpy=2.0.1=py312hfd52020_1
  - numpy-base=2.0.1=py312h4dde369_1
  - openssl=3.0.18=h543e019_0
  - pandas=2.2.3=py312h5da7b33_0
  - pip=25.1=pyhc872135_2
  - pycparser=2.21=pyhd3eb1b0_0
  - python=3.12.9=h14ffc60_0
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python-dotenv=1.1.0=py312haa95532_0
  - python-engineio=4.12.2=py312haa95532_0
  - python-socketio=5.13.0=py312haa95532_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - setuptools=78.1.1=py312haa95532_0
  - simple-websocket=1.1.0=py312haa95532_0
  - simplejson=3.19.2=py312h827c3e9_1
  - six=1.17.0=py312haa95532_0
  - sqlalchemy=2.0.39=py312h54f65d0_0
  - sqlite=3.45.3=h2bbff1b_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.14=h5e9d12e_1
  - tornado=6.5.1=py312h827c3e9_0
  - typing-extensions=4.12.2=py312haa95532_0
  - typing_extensions=4.12.2=py312haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - werkzeug=3.1.3=py312haa95532_0
  - wheel=0.45.1=py312haa95532_0
  - wsproto=1.2.0=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - amqp==5.3.1
      - antlr4-python3-runtime==4.9.3
      - beautifulsoup4==4.13.4
      - billiard==4.2.1
      - celery==5.5.3
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1
      - click-repl==0.3.0
      - coloredlogs==15.0.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - filelock==3.20.0
      - flask-jwt-extended==4.7.1
      - flask-mail==0.10.0
      - flatbuffers==25.9.23
      - flower==2.0.1
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - humanfriendly==10.0
      - humanize==4.12.3
      - idna==3.10
      - kiwisolver==1.4.9
      - kombu==5.5.4
      - matplotlib==3.10.7
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - mysqlclient==2.2.7
      - networkx==3.5
      - omegaconf==2.3.0
      - onnx==1.19.1
      - onnxruntime==1.23.2
      - opencv-python==4.12.0.88
      - openpyxl==3.1.5
      - packaging==25.0
      - pillow==12.0.0
      - polars==1.35.1
      - polars-runtime-32==1.35.1
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.51
      - protobuf==6.33.0
      - psutil==7.1.2
      - pyjwt==2.10.1
      - pyparsing==3.2.5
      - pyreadline3==3.5.4
      - pytz==2025.2
      - pyyaml==6.0.3
      - redis==6.2.0
      - requests==2.32.4
      - scipy==1.16.3
      - soupsieve==2.7
      - sympy==1.14.0
      - task-service==0.0.0
      - torch==2.9.0
      - torchvision==0.24.0
      - ultralytics==8.3.223
      - ultralytics-thop==2.0.18
      - urllib3==2.5.0
      - vine==5.1.0
      - wcwidth==0.2.13
prefix: D:\Anaconda3\envs\flask_web
